### PR TITLE
Wenmerge Mainnet Relay Updated on MEV-relay-list.md

### PR DESCRIPTION
**Pull request by cexedev**
In Mev-relay-list, Wenmerge meinnet relay added as a new row with relay information and Wenmerge goerli relay address updated

### CODE REVIEW

**Comment by sandakersmann** [comment]
Can you change Goerli to Wenmerge as well?

**Comment by sandakersmann** [comment]
It's Wenmerge on Twitter: https://twitter.com/Wenmerge2022

**Comment by cexedev** [comment]
@sandakersmann 
> Can you change Goerli to Wenmerge instead of Wen Merge?
Hi, thank you so much for pointing out. 
I had completely missed that. Now, I've fixed that  and pushed it in the commit
https://github.com/eth-educators/ethstaker-guides/pull/84/commits/4404654b16cd5410694d0bd31bc438aecffc0b6e


> It's Wenmerge on Twitter: https://twitter.com/Wenmerge2022
Yes, Now all the `Wen Merge` are changed to `Wenmerge`.

Again, Thank you so much

**Comment by cexedev** [comment]
@remyroy 
> Is there a consistent way to spell Wenmerge? It's spelled differently in your changes: `Wen Merge` in the Goerli section and `Wenmerge` in the Mainnet section.

Thank you so much for pointing this. And, so sorry making this mistake.
Now that you've pointed this out. I've change all the occurrences of `Wen Merge` and other inconsistencies to `Wenmerge`.

Again, Thank you so much.

**Pull request merged**
