### PR TITLE
Update naming of bloXroute

### PR DESCRIPTION
**Pull request by sandakersmann**
Update naming of bloXroute

### CODE REVIEW

**Comment by remyroy** [comment]
The first column is the Operator. We might want to rename that column to Operator/Relay Name or something like that if we want to include some relay *name*.

**Comment by sandakersmann** [comment]
Done

**Comment by randomishwalk** [comment]
@remyroy - do you think it is relevant context for ethstaker community to know if relay operators are known to be operating in multiple ecosystems (i.e. on ethereum-native rollups, sidechains, other L1 ecosystems etc)? just struck me as somewhat good to know. For example bloXroute I believe has been active across Solana and I think some other EVM chains (not sure if they have their services available on rollups yet)

**Comment by remyroy** [comment]
> @remyroy - do you think it is relevant context for ethstaker community to know if relay operators are known to be operating in multiple ecosystems (i.e. on ethereum-native rollups, sidechains, other L1 ecosystems etc)? just struck me as somewhat good to know. For example bloXroute I believe has been active across Solana and I think some other EVM chains (not sure if they have their services available on rollups yet)

I don't think it's relevant. We already have a link to the operator's website and users can do their own search from there.

**Comment by randomishwalk** [comment]
cool thanks

**Comment by remyroy** [comment]
Seems good. Thanks for the PR.

**Pull request merged**
