### PR TITLE
Update Blocknative Builders & Searchers section

### PR DESCRIPTION
**Pull request by laurencedelisle**
updated to accepting searcher bundles

### CODE REVIEW

**Comment by remyroy** [comment]
Where did you get that information? I just want to make sure we have a good source.

**Comment by randomishwalk** [comment]
@remyroy - will ask someone from blocknative to confirm this. hadn't seen this myself (not personally affiliated with blocknative or a user of their services)

**Comment by dmarzzz** [comment]
@remyroy @randomishwalk thanks for the double check! this information is valid, [we opened up permissionless bundle support Jan 11th](https://twitter.com/blocknative/status/1613284223653384193?s=20&t=7ZvkwX5obbC374WZ4GdSiQ).

**Comment by laurencedelisle** [comment]
@remyroy @randomishwalk thanks for the double check! It was also announced on our discord [here](https://discord.com/channels/542403978693050389/1044285339646312520/1062825343884476488)

**Comment by remyroy** [comment]
Seems good. Merging.

**Pull request merged**
