### PR TITLE
Update MEV-relay-list.md for Manifold Finance

### PR DESCRIPTION
**Pull request by randomishwalk**
Sourced from docs, github, and public comments. Manifold team should verify

### CODE REVIEW

**Comment by remyroy** [comment]
According to the lates Manifold issue, it seems like they are not validating their payload. It seems like they are blindly passing it along. https://twitter.com/toghrulmaharram/status/1581403353846013952

**Comment by sandakersmann** [comment]
I think we should merge this now

**Comment by remyroy** [comment]
This cannot be merge in the current state because the Manifold Finance relay was removed from our list for the time being. We are constantly observing the MEV offerings for validators. We will keep updating the list with what we think is good for the community.

**Comment by sandakersmann** [comment]
I think Manifold Finance should be added back in.

**Comment by remyroy** [comment]
> I think Manifold Finance should be added back in.

Is there an official statement somewhere that explains what happened recently, what was the cause of the issue, how it was handled with their relay users and how it will be prevented in the future?

**Comment by randomishwalk** [comment]
There has not been a detailed post-mortem as far as I can tell. So @remyroy agree with your recommendation here to not merge this PR until further clarity from the Manifold team. The health of validators/proposers should be prioritized at the moment.

**Comment by randomishwalk** [comment]
@remyroy - any updated thinking from your side / the ethstaker community more broadly now that relay issues seem to be behind us + there being additional clarity around what happened in mid-Oct?

**Pull request closed without merging**
