### PR TITLE
Update MEV-relay-list.md for Manifold Finance

### PR DESCRIPTION
**Pull request by randomishwalk**
@remyroy - any updated thinking from your side / the ethstaker community more broadly now that relay issues seem to be behind us + there being additional clarity around what happened in mid-Oct?

Apologies for closing the other PR, hadn't realized you had already made some updates to the relay list readme file!

Link to previous related PR below:
[Update MEV-relay-list.md for Manifold Finance #50 ](https://github.com/eth-educators/ethstaker-guides/pull/50#issue-1408055307)

### CODE REVIEW

**Comment by randomishwalk** [comment]
Link to recent Lido gov forum thread discussing this topic for reference: https://research.lido.fi/t/lido-on-ethereum-relay-voting-proposal/3135/11

Link to Sam Bacha's HackMD post-mortem note regarding the 10/15/22 relay incident: https://hackmd.io/@manifoldx/2022-10-15

**Comment by remyroy** [comment]
Thanks for these references. We'll discuss this internally.

**Comment by sambacha** [comment]
the discord link should not be used, the forums are our preferred method of community engagement

**Comment by sambacha** [comment]
the relay should be permissionless now as well

**Comment by randomishwalk** [comment]
Thanks @sambacha - you should see those changes reflected here now in the 2nd commit

**Comment by remyroy** [comment]
This seems good. We'll be merging this and we'll add some notes on the recent events and issues with Manifold Finance.

**Comment by randomishwalk** [comment]
> This seems good. We'll be merging this and we'll add some notes on the recent events and issues with Manifold Finance.

Thank you Remy and yes, important to flag those things. 

On that point -- do you have an existing set of notes or some tracker that tracks the (very brief) history of relay incidents across the ones currently on your list?

**Comment by remyroy** [comment]
We don't have any good record of MEV relay incidents. It's somewhat outside the scope of what we want to do here. It would be great if MEV relays would be self-reporting this on their own or if we could have another community project dedicated for this.

**Comment by randomishwalk** [comment]
Got it. Agree would be a good, separate community project. I don't expect to rely on the goodwill of relay operators so tapping into the community to crowdsource this would be a nice effort

**Pull request merged**
